// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcFQ26hwHvxC02U3p-ifW3o4QBer3OW1o',
    appId: '1:169143241949:web:4a39af7e4742821677df34',
    messagingSenderId: '169143241949',
    projectId: 'barbershops-c27c4',
    authDomain: 'barbershops-c27c4.firebaseapp.com',
    storageBucket: 'barbershops-c27c4.appspot.com',
    measurementId: 'G-2TJZPZ1C0X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy28P92whcsOT4tXxaMLFF8BAp0NXCOh0',
    appId: '1:169143241949:android:3230536cb9d376e477df34',
    messagingSenderId: '169143241949',
    projectId: 'barbershops-c27c4',
    storageBucket: 'barbershops-c27c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBx5ut4BwL0f3Y8-HgP49g2ILrgvpOfLCM',
    appId: '1:169143241949:ios:bd772e3e1c42dfbf77df34',
    messagingSenderId: '169143241949',
    projectId: 'barbershops-c27c4',
    storageBucket: 'barbershops-c27c4.appspot.com',
    iosBundleId: 'com.example.barberApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBx5ut4BwL0f3Y8-HgP49g2ILrgvpOfLCM',
    appId: '1:169143241949:ios:c712531b6b180ef377df34',
    messagingSenderId: '169143241949',
    projectId: 'barbershops-c27c4',
    storageBucket: 'barbershops-c27c4.appspot.com',
    iosBundleId: 'com.example.barberApp.RunnerTests',
  );
}
